### ISSUE TITLE
[BUG]:  minimum version OctoPrint 1.5.0 ?

### ISSUE THREAD

**Issue by ViPeR5000** [jneilliii/OctoPrint-GoogleDriveBackup#12]
minimum version OctoPrint 1.5.0 ? but Octoprint is in version 1.4.2

**Comment by jneilliii** [comment]
That is correct. 1.5.0 is currently in release candidate stages and will be available as a stable release upgrade soon, maybe this upcoming week. You could switch your release channel in octoprint to maintenance/rc and get the latest 1.5.0rc3 now if you want, link below explains how to do that.

https://community.octoprint.org/t/how-to-use-the-release-channels-to-help-test-release-candidates/402?u=jneilliii
