### ISSUE TITLE
[FR] Ability to customize file name

### ISSUE THREAD

**Issue by emklein** [jneilliii/OctoPrint-GoogleDriveBackup#19]
Is your feature request related to a problem? Please describe.
When uploading to a version control software such as Google Drive, if the file had the same name, it could iterate the version instead of making a new file with the timestamp every time. Currently it creates a ton of backups that I have to regularly go in and delete once they are obsolete and I know I don't need them.

Describe the solution you'd like
Output the file with a generic file name so that it versions the same file in google drive instead of creating a new file every time it exports, reducing drive clutter and obsolete files.

Describe alternatives you've considered
None

Additional context
None

**Comment by jneilliii** [comment]
The plugin itself doesn't actually do the work of the backup, it only reacts to backup events, which passes the filename as a parameter to this plugin's code. I do like the idea you propose though, where maybe the timestamp gets stripped off of the name while uploading to Google Drive.

**Comment by jneilliii** [comment]
Option to strip the timestamp from the backup filename, basically allowing for uploading as new version every time a backup is generated added with the above commit. Releasing as 0.0.4rc1 for testing, change the release channel for the plugin in Software Update setting to `Release Candidate` and install the upgrade when prompted to do so.

**Comment by emklein** [comment]
Worked perfectly in my testing. Successfully overwrote the previous file and Google Drive saved it as the next version. 

Thank you very much for this, I appreciate your work for the community!
