### ISSUE TITLE
Backups error out

### ISSUE THREAD

**Issue by bepstein111** [jneilliii/OctoPrint-GoogleDriveBackup#20]
Installed this a while ago and just today realized none of my backups were on my google drive. I went to check my logs, and found this:

`2021-06-27 14:02:06,994 - octoprint.plugins.googledrivebackup - INFO - /home/bep/.octoprint-cr10/data/backup/BepBot-V2.2-backup-20210627-140100.zip created, will now attempt to upload to Google Drive
2021-06-27 14:02:07,315 - octoprint.plugin - ERROR - Error while calling plugin googledrivebackup
  File "/home/bep/OctoPrint/venv/lib/python3.8/site-packages/octoprint_googledrivebackup/__init__.py", line 92, in on_event`

Unsure how to proceed from here, advice would be helpful. Thanks!

**Comment by jneilliii** [comment]
please share your full log so I can get the details of the entire error and not just that little snippet.

**Comment by bepstein111** [comment]
Was pretty sure that was the only relevant piece. Here you go. 

[octoprint.log](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup/files/6722118/octoprint.log)

**Comment by jneilliii** [comment]
yeah, looks like you need to just clear the auth, and re-upload your client_secret.json.
