### ISSUE TITLE
No new uploads to my Gdrive after 7 days

### ISSUE THREAD

**Issue by Pestage** [jneilliii/OctoPrint-GoogleDriveBackup#26]
Hi, I have an issue with your plugin.
It was working fine the first seven days but now I don't see any new Octo backups on my Gdrive.
If you have an idea why this is happening.
Thanks.

Regards.

**Comment by jneilliii** [comment]
Do you see any errors in octoprint.log?

**Comment by Pestage** [comment]
Nope everything seems fine. Do you have some logs to check in your plugin ?

**Comment by jneilliii** [comment]
You should see entries in octoprint.log every time you do a backup in octoprint where it uploads once the backup is completed locally.

**Comment by Pestage** [comment]
Ah sorry, I didn't look at the bottom of the log file ! I feel like a newbie lol.

> 2021-11-25 17:43:36,657 - octoprint.plugins.backup - INFO - Creating backup zip at /home/pi/.octoprint/data/backup/.octoprint-backup-20211125-174336.zip (excluded: timelapse,timelapse_tmp)...
> 2021-11-25 17:43:36,777 - octoprint.plugins.backup - INFO - ... done creating backup zip.
> 2021-11-25 17:43:36,783 - octoprint.plugins.googledrivebackup - INFO - /home/pi/.octoprint/data/backup/octoprint-backup-20211125-174336.zip created, will now attempt to upload to Google Drive
> 2021-11-25 17:43:37,582 - octoprint.plugin - ERROR - Error while calling plugin googledrivebackup
> Traceback (most recent call last):
>   File "/home/pi/oprint/lib/python3.7/site-packages/pydrive2/auth.py", line 544, in Refresh
>     self.credentials.refresh(self.http)
>   File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 545, in refresh
>     self._refresh(http)
>   File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 761, in _refresh
>     self._do_refresh_request(http)
>   File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
>     raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
> oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Bad Request

Here I can see that something is failing with the auth but I didn't change the password strange.
I just tried to delink and relink the plugin with my Gdrive and it's working.
I use a Gscript to schedule the move of the log file to a ddedicated subfolder every day at night.
I will check tomorrow and 7 days after if the auth issue is back or not.

Thanks for your help.

**Comment by Pestage** [comment]
Hi, this time it's fine :)
No disconnection with my Gdrive
I just have to modify my Gscripts to keep only the 10 last backup files.

**Comment by jneilliii** [comment]
If you switch the release channel of the plugin to Release Candidate in OctoPrint's software update settings and update when prompted there are some additional options that will allow you to strip the time stamps and it will just overwrite the file on upload. This will allow Google Drive's history to basically keep your previous ones for you in revision history.

**Comment by jneilliii** [comment]
now that I think about it, I'll just release these changes stable. I've been running it for some time with no issues.

**Comment by Pestage** [comment]
Hi, hmm in fact, I have the same issue. Same logs :

```
2021-12-04 22:00:11,946 - octoprint.plugins.googledrivebackup - INFO - /home/pi/.octoprint/data/backup/octoprint-daily-20211204-220011.zip created, will now attempt to upload to Google Drive
2021-12-04 22:00:13,288 - octoprint.plugin - ERROR - Error while calling plugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/pydrive2/auth.py", line 544, in Refresh
    self.credentials.refresh(self.http)
  File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/home/pi/oprint/lib/python3.7/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 92, in on_event
    gauth.Refresh()
  File "/home/pi/oprint/lib/python3.7/site-packages/pydrive2/auth.py", line 546, in Refresh
    raise RefreshError("Access token refresh failed: %s" % error)
pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.


```

I think the issue is with the token timeout. I will check.

**Comment by jneilliii** [comment]
That would make sense. If you set an expiration on your token then it would make sense that the plugin would stop working after the token expired.

**Comment by Pestage** [comment]
Hmm I will check but it can be because I had set my application in Test mode on Google Cloud Platform.
I just put it in production mode and created a manual backup. It failed.
I will redo the authentification to see what happens in next days.
