### ISSUE TITLE
Improve Description

### ISSUE THREAD

**Issue by ashleycawley** [jneilliii/OctoPrint-GoogleDriveBackup#3]
Hopefully an easy one for you; please make it more explicit / obvious in your OctoPrint Plugin description and Github docs as to what exactly it is backing up for the user.

Is this backing up a single print job GCODE after a successful print? Or is this backing up the whole OctoPrint configuration or something in between? I'm not sure. If its more obvious to readers then perhaps more users will install it and give it a go.

Thanks for your time on this one!

**Comment by jneilliii** [comment]
Hey Ashley, this plugin is kind of an auxiliary tool to the default backup plugin that is bundled with OctoPrint. Basically what it does is upload any backup you create manually or through my new backup scheduler plugin to your google drive. If you choose to include gcode files or timelapses, those are included in the backup, etc.

**Comment by jneilliii** [comment]
And BTW it won't work until future version OctoPrint 1.5.0 anyway, so might not be something you'll be able to use until the next official release.

**Comment by cyberfilou** [comment]
Hello
In addition, version 1.5.0 is not yet available, so why release this plugin if it does not work yet?
Thank you

**Comment by jneilliii** [comment]
There are some people running 1.5.0, mostly developers like myself, where the feature is available already.
