### ISSUE TITLE
Octoprint just opens a new instance instead of loading Authntication

### ISSUE THREAD

**Issue by TyriqueDaniel** [jneilliii/OctoPrint-GoogleDriveBackup#35]
Tried to generate  auth code but it just opens a new instance i have already verified my google account

Ive tried clearing cache and using a new browser

**Comment by jneilliii** [comment]
Clear the plugin's settings using the eraser icon in plugin manager.

**Comment by jneilliii** [comment]
Enable debug logging for the plugin in OctoPrint's logging section of settings and share octoprint.log here.
