### ISSUE TITLE
backups files not create in sub folder

### ISSUE THREAD

**Issue by razserv2010** [jneilliii/OctoPrint-GoogleDriveBackup#36]
like this: octoprint/Artillery Hornet
and the plugin thinks that this "octoprint/Artillery Hornet" is the name of the folder

Thank you! , Love the plugin, for alerts I use IFTTT and as soon as a new file pops up in the folder then I get an email alert.

**Comment by jneilliii** [comment]
Are you trying to put it in a sub-folder of a sub folder? Try including the `/` at the end, ie `octoprint/Artillery Hornet/` maybe? Another option for keeping multiple printer separated is changing the Title setting in OctoPrint's Appearance settings and the backup file will be named based on that setting.

**Comment by colwellkr** [comment]
FYI, this is still an issue. Adding a trailing slash `/` does not fix that you cannot store more than one folder deep from root. (IE. `Backups/Octoprint`).

**Comment by jneilliii** [comment]
Thanks for the pointer, I have a similar function call in this plugin and I suspect it just needs to be made recursive for the additional `/`.

**Comment by mich0111** [comment]
Hi,
Same issue.
Just a message to follow this topic.

**Comment by mbalasz** [comment]
Hi,

This issue is still present in the latest version.

Any plans to fix this?

**Comment by jneilliii** [comment]
Eventually, I just haven't had much time lately for plugin development.

**Comment by TinkerNinja** [comment]
Would really appreciate to be able to set the folder ID instead of a string. this would allow to use a folder in a shared drive as well

**Comment by jneilliii** [comment]
So, I'm looking at the code again and in theory if you have an existing folder that is writable, shared or not, if the configured folder name in the plugin's settings matches the plugin should find it. The one caveat to that is if there are multiple folders with the same name, then the plugin will use the first one found for processing. I'm still looking into a possible recursive approach to a provided path in the settings, ie `OctoPrint Backups/Printer1`, but in my experience I've been able to handle multiple printers by adjusting the title setting in OctoPrint's appearance settings to have unique zip file names.

**Comment by jneilliii** [comment]
I've been able to make the folder creation/upload recursive using linux style folder pathing, ie `OctoPrint/Backups/Printers/1`

**Comment by TinkerNinja** [comment]
Thanks a bunch for this - sub folders is working great !!
However for my purpose I actually need to store them in 'Shard folders' will create a new issue for this.
