### ISSUE TITLE
Google ending support for OAuth out-of-band (OOB) flow 2022-10-03

### ISSUE THREAD

**Issue by terrencegf** [jneilliii/OctoPrint-GoogleDriveBackup#37]
I received the following email from Google Developers indicating that support for [OAuth out-of-band (OOB)](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob) will be deprecated October 3, 2022. Note that apps using OOB in testing mode will not be affected, but apps in production mode will be impacted. 

----

Hello Google OAuth Developer,

We are writing to inform you that OAuth out-of-band (OOB) flow will be deprecated on **October 3, 2022**, to protect users from phishing and app impersonation attacks.

## What do I need to know?

Starting **October 3, 2022**, we will block OOB requests to Google’s OAuth 2.0 authorization endpoint for existing clients. Apps using OOB in [testing](https://support.google.com/cloud/answer/10311615#publishing-status&zippy=%2Ctesting) mode will not be affected. However, we strongly recommend you to migrate them to safer methods as these apps will be immediately blocked when switching to [in production](https://support.google.com/cloud/answer/10311615#publishing-status&zippy=in-production) status.

**Note**: New OOB usage has already been disallowed since **February 28, 2022**.

### Below are key dates for compliance

    September 5, 2022: A user-facing warning message may be displayed to non-compliant OAuth requests
    October 3, 2022: The OOB flow is blocked for all clients and users will see the error page.

Please check out our recent blog post about [Making Google OAuth interactions safer](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html) for more information.

### Migrate your app(s) to an appropriate alternative method by following these instructions:

1. Determine your app(s) [client type](https://support.google.com/cloud/answer/6158849#zippy=%2Cnative-applications%2Cweb-applications) from your Google Cloud project by following the client links below.
2. Migrate your app(s) to a more secure alternative method by following the instructions in the blog post above for your client type.

If necessary, you may request a [one-time extension](https://docs.google.com/forms/d/e/1FAIpQLScjUSVDPIFcxCMRJ0G0_UQ8YwaJIMSr--WKQbr2zMqE737RYg/viewform) for migrating your app until **January 31, 2023. Keep in mind that all OOB authorization requests will be blocked on February 1, 2023.**

The following OAuth client(s) will be blocked on Oct 3, 2022.

### OAuth client list:

- Project ID: \<redacted\>
   - Client: \<redacted\>

Thanks for choosing Google OAuth.

**— The Google OAuth Developer Team**

**Comment by jneilliii** [comment]
Yeah, I received the same notice. Luckily I've already made the changes necessary. On your end all you will need to do is log back into the Google Developer Console and re-create your credential following the configuration guide starting at step 12 [here](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup#configuration). Once you download your client_secrets.json file go into the plugin's settings and click the delete button and then upload the new one to authorize.
