### ISSUE TITLE
Missing Authorized Redirect URI 

### ISSUE THREAD

**Issue by therealdjryan** [jneilliii/OctoPrint-GoogleDriveBackup#38]
You get the error "**Missing Authorized Redirect URI** " If the Authorized Redirect URI does not end in a '/'

I had to go into the debugger to figure this out. If the slash is important, then the error should say what the problem is. However if the slash isn't important  you might strip it off from the json response:
```json_data["web"]["redirect_uris"][0].replace(/\/$/,"")  !== 'https://jneilliii.github.io/OctoPrint-GoogleDriveBackup'```

Another observation is that you are only testing the first element in the array. This may or may not be important to you.

Thanks, I appreciate your efforts on the really nice plugin.

**Comment by jneilliii** [comment]
IIRC the slash at the end is critical, and why it's documented that way in step 13. Adding a little more clarification to the error message would make sense.

**Comment by mich0111** [comment]
Hi,
Thx for your plugin.
I have the same issue
`Missing Authorized Redirect URI "https://jneilliii.github.io/OctoPrint-GoogleDriveBackup/" in [step 15](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup#create-a-google-oauth-app).`

I have checked and here are the informations in the credentials :

```
URI de redirection autorisés
À utiliser avec les requêtes provenant d'un serveur Web
URI 1 
https://jneilliii.github.io/Octoprint-GoogleDriveBackup/
```

So it seems the URL is correct.
Could you please indicate to me what's wrong ?

Best regards

Michel

**Comment by jneilliii** [comment]
open your client.json file in a text editor and verify that it shows that URL in the redirect_uris field.

**Comment by jneilliii** [comment]
ah, I see the issue. it's case sensistive, so make sure it's like this...(capital P in OctoPrint. 

```
https://jneilliii.github.io/OctoPrint-GoogleDriveBackup/
```

**Comment by mich0111** [comment]
Hi,

 

I changed the URL and here are the redirected URL in the json file :

"redirect_uris":["https://jneilliii.github.io/OctoPrint-GoogleDriveBackup/"]

 

So, it seems it’s ok.

 

Unfortunately, after the upload of the json file and the “save” of the configuration, none window for the Drive access is opened.

Could you please tell me how to authorize the access to Google Drive and is it possible to schedule the backup with your plugin ?

 

Best regards

 

Michel

 

De : jneilliii ***@***.***> 
Envoyé : mardi 6 juin 2023 00:33
À : jneilliii/OctoPrint-GoogleDriveBackup ***@***.***>
Cc : Michel C (mich0111) ***@***.***>; Comment ***@***.***>
Objet : Re: [jneilliii/OctoPrint-GoogleDriveBackup] Missing Authorized Redirect URI (Issue #38)

 

ah, I see the issue. it's case sensistive, so make sure it's like this...(capital P in OctoPrint.

https://jneilliii.github.io/OctoPrint-GoogleDriveBackup/

**Comment by jneilliii** [comment]
check octoprint.log for errors. this plugin is solely for uploading backups to Google Drive. For scheduling see my other plugin, they both work in combination. 

https://plugins.octoprint.org/plugins/backupscheduler/

**Comment by mich0111** [comment]
Hi,

 

Here is the octoprint.log.

I don’t understand it.

Could you help me ?

 

I use your other plugin “Backup Scheduler” and I have no problem with. It works very well.

My question is, how does your Google Drive Backup plugin work ?

Does it make an upload each time a new file appears or have I to run something to launch the uploads ?

 

Best regards

 

Michel 

 

De : jneilliii ***@***.***> 
Envoyé : mardi 6 juin 2023 03:39
À : jneilliii/OctoPrint-GoogleDriveBackup ***@***.***>
Cc : Michel C (mich0111) ***@***.***>; Comment ***@***.***>
Objet : Re: [jneilliii/OctoPrint-GoogleDriveBackup] Missing Authorized Redirect URI (Issue #38)

 

check octoprint.log for errors. this plugin is solely for uploading backups to Google Drive. For scheduling see my other plugin, they both work in combination.

https://plugins.octoprint.org/plugins/backupscheduler/

**Comment by mich0111** [comment]
Hi,
Since your last message, I have made a "pip install PyDrive2" but it didn't change anything.
Here is the new octoprint.log
Regards
Michel
[octoprint.log](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup/files/11665610/octoprint.log)
