### ISSUE TITLE
[BUG]: Not backing up

### ISSUE THREAD

**Issue by soates1127** [jneilliii/OctoPrint-GoogleDriveBackup#4]
**Describe the bug**
Nothing is getting sent to GoogleDrive after the print completes

**Expected behavior**
A copy of the gcode file gets uploaded to GoogleDrive
**Debug Log**

**Screenshots**
N/A

**Firmware and Version**
OctoPrint 1.4.2

I followed all the developer steps, and put the key in the plugin.  it activated but still doesn't upload/send anything to GoogleDrive

**Comment by jneilliii** [comment]
Please see prerequisites, the plugin only works on OctoPrint 1.5.0 or higher, which is currently in active development.

https://github.com/jneilliii/OctoPrint-GoogleDriveBackup#octoprint-150
