### ISSUE TITLE
Access blocked: jneilliii.github.io has not completed the Google verification process

### ISSUE THREAD

**Issue by Tareq-Assiri** [jneilliii/OctoPrint-GoogleDriveBackup#43]
jneilliii.github.io has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the [developer](https://accounts.google.com/).
If you are a developer of jneilliii.github.io, see [error details](https://accounts.google.com/).
Error 403: access_denied

**Comment by jneilliii** [comment]
Did you complete step 9 [here](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup#create-a-google-oauth-app) and your mode is still in test? Because of some limitations with Google's API you may need to switch your app in Google to production instead of test.

**Comment by jneilliii** [comment]
The reason I mention publishing the app is because I think recent changes to the client secrets on test apps will always expire after 2 weeks, so you'll have to keep getting a new secrets.json and re-add it to the plugin over and over.

**Comment by Tareq-Assiri** [comment]
publishing it fixed it .
Thanks for such a great plugin and support :)
