### ISSUE TITLE
Upload button does not trigger a response

### ISSUE THREAD

**Issue by DiP-ER** [jneilliii/OctoPrint-GoogleDriveBackup#49]
After clicking 'Browse' and selecting the client_secrets.json file, I press 'Upload' but nothing appears to happen.  I am never presented with a URL to authorize the Google app.  Any help is appreciated.

**Comment by jneilliii** [comment]
Check octoprint.log for errors after restarting OctoPrint from the system menu. I suspect that your install failed and there will be manual steps that you will have to take in order to resolve.

**Comment by DiP-ER** [comment]
Looking at the logs I see the following dealing with Google Drive:

2023-01-17 14:10:31,610 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin googledrivebackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup/__init__.py", line 38, in on_api_command
    from pydrive2.auth import GoogleAuth
ModuleNotFoundError: No module named 'pydrive2'

**Comment by jneilliii** [comment]
Yeah, you're running into the issue created by cryptography install failure (upstream dependency of pydrive2). To resolve uninstall the plugin using the option to clear data, then SSH to the pi and run these commands: 

```
sudo apt update
sudo apt upgrade
sudo apt remove rustc
curl https://sh.rustup.rs/ -sSf | sh
```
use the default options that load and after installation completes reboot with the command `sudo reboot`
```
/home/pi/oprint/bin/pip install cryptography
/home/pi/oprint/bin/pip install pydrive2
```

**Comment by DiP-ER** [comment]
Yep.  That did the trick.  Thanks!
