### ISSUE TITLE
When I upload the json file Nothing Happens

### ISSUE THREAD

**Issue by vulgerrity** [jneilliii/OctoPrint-GoogleDriveBackup#50]
I've followed the instructions multiple times, and when I upload the Client Secrets JSON file, nothing ever happens.  I can't get it to connect to my Google Drive account :(

**Comment by jneilliii** [comment]
please share octoprint.log if you want me to debug this issue for you.

**Comment by vulgerrity** [comment]
[octoprint_20230416-1144.log](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup/files/11242867/octoprint_20230416-1144.log)

Thank you!

**Comment by vulgerrity** [comment]
It looks like pydrive2 is not found?

**Comment by jneilliii** [comment]
that typically mean a failed install of pydrive2 because of a cryptography dependency. check this issue thread on possible solutions. https://github.com/jneilliii/OctoPrint-GoogleDriveBackup/issues/16

**Comment by vulgerrity** [comment]
So, I tried doing what I found in the thread you linked, but it ended up breaking my octoprint install for some reason.  I just did a fresh install of OctoPrint and your plugin works right out of the box.  Not sure what was going on, but it's working now.  Thanks!

**Comment by jneilliii** [comment]
that's odd, sorry it broke your OctoPrint but glad you got it worked out.
