### ISSUE TITLE
Cannot install pydrive2 (Raspberry PI3A+)

### ISSUE THREAD

**Issue by spanzetta** [jneilliii/OctoPrint-GoogleDriveBackup#51]
System details:
OctoPrint 1.9.0 
Python 3.9.2 
OctoPi 1.0.0

When try to install PyDrive2 (_pip install pydrive2_) it says

_Python: 3.9.2
          platform: Linux-6.1.21-v7+-armv7l-with-glibc2.31
          pip: n/a
          setuptools: 67.8.0
          setuptools_rust: 1.6.0
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler_

but if I run "_rustc --version_" the output is
_rustc 1.69.0 (84c898d65 2023-04-16)_

What's wrong?

Can someone pls help?

Thanks

**Comment by jneilliii** [comment]
Recent issue with cryptography not building again in piwheels. Version 40.0.1 was last successful. Try running `/home/pi/oprint/bin/pip install cryptography==40.0.1` followed by `/home/pi/oprint/bin/pip install pydrive2`.

**Comment by spanzetta** [comment]
Thanks for the suggestion.. 

Before I had ver 36.. now installed 40.0.1 (even if during setup of PyDrive2 I read at some point "using cached cryptograpgy 41.0.0.tar.gz"

Now setup stucks at "Building wheel for cryptography (pyproject.toml)".. it stays there forever.

Some other hints?

Thanks

**Comment by spanzetta** [comment]
I see that even if I install the build 40.0.1 as you suggested ... and I do a purge to clean the 41.0.0.. when pydrive2 setup starts it install anyway ver 41.0.0..
Is that the cause of the problem? How to fix?

**Comment by jneilliii** [comment]
It could be, if pydrive2 has pinned their dependencies to the newest version. the critical part here is that you install the cryptography version within the venv that OctoPrint is running, and without knowing your setup it's hard for me to say. The path/commands I provided above were assuming an octopi image.

**Comment by spanzetta** [comment]
I have the Octopi image (wrote at beginning)

System details:
OctoPrint 1.9.0
Python 3.9.2
OctoPi 1.0.0

**Comment by spanzetta** [comment]
I can remove it by using this command
_rustup self uninstall_

**Comment by spanzetta** [comment]
I give up..
After 2 days trying to make it working, asking also help to ChatGPT (tried all its suggestions) I found no way to resolve..
It's sad because it's the 1st plugin out of more then 30 that I wasn't able to have it working. 

I then tried OneDrive backup plugin and in 3 minutes I was able to configure and have it up and running (the setup did configure everything.. without any manual steps as prerequisite.. )

I will use that one instead of GoogleDrive backup plugin

Thanks anyway

**Comment by jneilliii** [comment]
Yeah, sorry I couldn't help you more. The OneDrive API is way easier to deal with than the Google one and every time cryptography builds fail on piwheels causes a break in the plugin. I've been dealing with it since plugin inception so consider my frustration.

**Comment by spanzetta** [comment]
For your information..  I am using a similar plugin for my Home Assistant server (it's installed on my second Raspberry... same HW of my OctoPrint server) and I had not difficult at all to install it..
Take a look at it.. maybe you can find a way to make it simpler to install..
https://github.com/sabeechen/hassio-google-drive-backup

**Comment by jneilliii** [comment]
Thanks, looks like they're using the Google modules directly. May investigate switching to this as time permits.
