### ISSUE TITLE
Support 'Shared Drives'

### ISSUE THREAD

**Issue by TinkerNinja** [jneilliii/OctoPrint-GoogleDriveBackup#53]
Add support for 'Shard drives' - following from #36 it would be great if I can use a 'Shared Drive' to store the backups instead of only 'My Drive'

**Comment by jneilliii** [comment]
I may need some assistance from you in this venture. Can you share a folder from your drive to my gmail (jneilliii) with edit permissions? As mentioned in the other issue I think you can get away with just the folder name, but need a shared folder in my account to verify, all the ones I have are read only.

**Comment by TinkerNinja** [comment]
very happy to help - my sysadmin just created a shared drive for development and added you as 'content manager'. Let me know if you need anything else....

**Comment by jneilliii** [comment]
0.1.3 version released with new option to use id instead of name. Grab the ID from the URL path in the browser and enter it in the Upload Folder setting and check the `use folder id instead of name` box and save.

**Comment by TinkerNinja** [comment]
Did I tell you - YOU ARE FANTASTIC !!!? 
works like a charm !!!
Thanks a bunch !

**Comment by jneilliii** [comment]
Consider supporting my efforts if you don't already. GitHub sponsorship, patreon, or PayPal available by clicking the Sponsor button at the top of Repo page: https://github.com/jneilliii/OctoPrint-GoogleDriveBackup
