### ISSUE TITLE
[FR]: Enable upload to a custom directory

### ISSUE THREAD

**Issue by Kiendeleo** [jneilliii/OctoPrint-GoogleDriveBackup#8]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a setting that allowed for a custom file path inside of Google Drive for the backups to be uploaded.

**Describe the solution you'd like**
Have a field in the setting that allowed for a custom path to be entered.  Then files would upload to the folder defined in this field.

**Describe alternatives you've considered**
None

**Additional context**
You may want to implement a folder browser as part of this to ensure that the folders are not mistyped.

**Comment by jneilliii** [comment]
makes total sense. do you think it would be best to have the option for every backup option so you can also separate daily, montly, yearly, and startup backups?

**Comment by Kiendeleo** [comment]
For my personal needs, I just wanted to have the ability to define a different G-Drive folder for each Octoprint instance as I have multiple printers with multiple Octoprint instances.  Although a subfolder for manual vs. scheduled saves might be a good idea.

**Comment by karelv** [comment]
For me I'm already happy when those files are not in the root of my gdrive. A single directory would do.
Thx!
:+1:

**Comment by jneilliii** [comment]
I be looking at this probably in the next few weeks. One thing that will change this @Kiendeleo in the future is that with OctoPrint 1.6.0 the backups will base the filename on the Appearance name setting within OctoPrint, which will help keep those separate as well. I tried pushing the changes in prior to 1.5.0 but didn't make it in time to be included.

**Comment by Kiendeleo** [comment]
A hardcoded folder, for example, OctoPrint Backups, would be better than dropping it in the root folder in my opinion, but I would still like to customize the folder through the use of a variable.

**Comment by spacecabbie** [comment]
> I be looking at this probably in the next few weeks. One thing that will change this @Kiendeleo in the future is that with OctoPrint 1.6.0 the backups will base the filename on the Appearance name setting within OctoPrint, which will help keep those separate as well. I tried pushing the changes in prior to 1.5.0 but didn't make it in time to be included.

Just like to offer if you need help debuging or testing i am quite familiar with gdrive api in usage.

**Comment by jneilliii** [comment]
@spacecabbie thanks for the offer. Quick question since you probably already know,  do you have to create a subfolder first to upload to our can you just upload with destination path and it figures it out?

**Comment by spacecabbie** [comment]
> @spacecabbie thanks for the offer. Quick question since you probably already know, do you have to create a subfolder first to upload to our can you just upload with destination path and it figures it out?
Well disclaimer I am not an advanced programmer especially not in Python. I am more familiar with the usage parts on google api's etc. 

Nevertheless, I went digging you do need to specify a folder and create it first. some info: https://stackoverflow.com/questions/30585166/create-a-folder-if-not-exists-on-google-drive-and-upload-a-file-to-it-using-py
As a possible work around:
`f = drive.CreateFile({'title': payload["name"]}{'parents': [{'id': 'put-folder-id-here'}]})`
I have not tested it yet (2day print running) but that should take care of it.

more examples: https://stackoverflow.com/questions/56434084/google-pydrive-uploading-a-file-to-specific-folder

Hope it helps if you need me to test anything let me know I am setting up a vm anyways was annoyed that i couldn't test this.

**Comment by Nomar383** [comment]
Would also love to see this added

**Comment by jneilliii** [comment]
Implemented with the above commit. I'll be releasing version 0.0.4rc2 shortly with these changes. If you'd like to test change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. Looking forward to your feedback.

**Comment by emklein** [comment]
Do you know if it is possible to path to an existing location? I tried a few syntax options ('\' vs '/') but it didn't appear to be able to place the file in an existing path I have. 

The path options I tried were (where Side Projects and 3D Printers are my folder/directory names):
- /Side Projects/3D Printer     ## Made a new folder at top Google Drive directory named '/Side Projects/3D Printer'
- /Side Projects/3D Printer/     ## Made a new folder at top Google Drive directory named '/Side Projects/3D Printer/'
- Side Projects/3D Printer     ## Made a new folder at top Google Drive directory named 'Side Projects/3D Printer'
- \Side Projects\3D Printer     ## Did nothing, no file created
- \Side Projects\3D Printer\     ## Did nothing, no file created
- Side Projects\3D Printer     ## Did nothing, no file created

It would definitely appear that backslashes are not valid folder names.

thanks, i appreciate your work for the community!

**Comment by jneilliii** [comment]
It currently only supports one level deep, in order to do a deeper path would require a pretty significant amount of work I think based on my experiences with the above changes.

**Comment by jneilliii** [comment]
@emklein I just figured out how you can use a sub folder. If you manually create the folder first where you want it in your Drive and then just use that folder's name in the plugin's settings, when the plugin checks to see if the folder exists it will find it. Only possible issue that I can see is if you have multiple folders with the same name in your Drive. In that case the plugin automatically uses the first one of the available folders returned with that name. So in your case create the folder `3D Printer` in `Side Projects`, and then set the plugin's custom folder as `3D Printer`.

**Comment by emklein** [comment]
@jneilliii that worked perfect. Thank you!
