### ISSUE TITLE
[FR]: Upload Progress Display

### ISSUE THREAD

**Issue by Kiendeleo** [jneilliii/OctoPrint-GoogleDriveBackup#9]
**Is your feature request related to a problem? Please describe.**
It would be cool to see a display of the progress of uploads in the settings window. 

**Describe the solution you'd like**
A list of backup files with a status (queued, uploading, completed, error)

**Describe alternatives you've considered**
None

**Additional context**
I like the extension please keep up the good work

**Comment by jneilliii** [comment]
Not sure I'm willing to spend the time to incorporate that scenario, if it's even possible to get the progress back as all the work is being done by a separate module.

**Comment by Kiendeleo** [comment]
Could you write to the Octoprint log as part of the trigger response and then parse the log to show the status of the file uploads?  I am trying to parse through your code and see what it does, but I have never written a plugin for Octoprint, so I am not sure how it all works.

**Comment by jneilliii** [comment]
So for any kind of interaction with the front end you would have to use something like [send_plugin_message](https://docs.octoprint.org/en/master/modules/plugin.html?highlight=send_plugin_message#octoprint.plugin.core.PluginManager.send_plugin_message) from the python side (assuming we can even get progress from the module I'm using), which is received by a calback on the js side via `onDataUpdaterPluginMessage` [viewmodel callback](https://docs.octoprint.org/en/master/plugins/viewmodels.html#callbacks). You would then assign the value based on the passed data to a knockout observable or possibly just direct interaction with the UI to move a progress bar.

**Comment by Kiendeleo** [comment]
I think I understand, maybe the best solution, for now, would be writing out to the module log file when the upload function is called. This would at least allow for some visibility on what the plugin is doing.

**Comment by jneilliii** [comment]
It writes to octoprint.log when it tries to upload [here](https://github.com/jneilliii/OctoPrint-GoogleDriveBackup/blob/187fc53f29b78ff4e311fc32e99ad990e05b4ac1/octoprint_googledrivebackup/__init__.py#L80)

**Comment by Kiendeleo** [comment]
Well, then I guess I did something wrong because I am able to create backups locally but the BackupGoogle Drive is not showing up in the log or uploading to my Google Drive

**Comment by jneilliii** [comment]
LOL...did you also run a development environment of OctoPrint 1.5.0. The plugin requires OctoPrint 1.5.0 at a minimum, as stated in the prerequisites.

**Comment by Kiendeleo** [comment]
I am not.  I overlooked that particular prerequisite.  Now to figure out how to change to the development environment... Google here I come

**Comment by jneilliii** [comment]
After looking into this more, it doesn't seem that the upload functions of PyDrive2 allow for a callback for progress, so this unfortunately will not be possible to accomplish. Now that the capability is available in the latest stable releases of OctoPrint closing this ticket.
